{
  "title": "Try... catch blocks[edit]",
  "content": "See also Throwing and Catching Exceptions.The try-catch blocks are used to catch any exceptions or other throwable objects within the code.Here's what try-catch blocks looks like:try {\n\nstatement1.1\nstatement1.2\n...\nstatement1.n\n\n} catch (exception1) {\n\nstatement2.1\n...\nstatement2.n\n\n}The code listing 3.6 tries to print all the arguments that have been passed to the program. However, if there not enough arguments, it will throw an exception.Code listing 3.6: Attempt.java\n\n\n 1 public class Attempt {\n 2   public static void main(String[] args) {\n 3     try {\n 4       System.out.println(args[0]);\n 5       System.out.println(args[1]);\n 6       System.out.println(args[2]);\n 7       System.out.println(args[3]);\n 8     } catch (ArrayIndexOutOfBoundsException e) {\n 9       System.out.println(\"Not enough arguments\");\n10     }\n11   }\n12 }In addition to the try and catch blocks, a finally block may be present. The finally block is always executed, even if an exception is thrown. It may appear with or without a catch block, but always with a try block.Here is what a finally block looks like:try {\n\nstatement1.1\nstatement1.2\n...\nstatement1.n\n\n} catch (exception1) {\n\nstatement2.1\n...\nstatement2.n\n\n} finally {\n\nstatement3.1\n...\nstatement3.n\n\n}"
}